### ISSUE TITLE
Getting Secret key for message not found. error when decrypt

### ISSUE THREAD

**Issue by kodehelp22** [mattosaurus/PgpCore#62]
Hi,
I'm getting the **Secret key for message not found** when i try to decrypt a encrypt and signed file.
I have attach my project so you can try.
I have a private key which i have generated and a public key from my external partner where i have to send the encrypt and signed file.
Then encryption part works fine, but when I try to decrypt the encrypt and signed file I get the metioned error.
I have checked that i'm using the right private key, password and i'm using the same private key for decryption which I used to encrypt.   

I have attached my C# project, just build it.

Try this flow:

PS. I have not attach the private and public key, because we use these keys in real test environment.

1. Point to your input file, private key and public key
2. Start the console app
3. press E for encryption
4. when the encryption and sign is finished press enter for exit.

now

1.Point to the same private key 
2. Start the console app
3. Press D for decryption
4. You will get the error.

Hope you can tell me why i'm getting this error.

[PGP_POC.zip](https://github.com/mattosaurus/PgpCore/files/4546893/PGP_POC.zip)

**Comment by mattosaurus** [comment]
Thanks for sending through an example to illustrate this :)

I'll try and have a look in the next day or two.

**Comment by mattosaurus** [comment]
I think this is because you're using an old version of the package (v1.2) and I've fixed a few bugs since then.

You project is in .NET Framework 4.7.2, if you're unable to upgrade it to .NET Core then I suggest updating the library to v2.2.0 which is the last version which worked with .NET Framework and will hopefully fix your issue.

**Comment by kodehelp22** [comment]
> I think this is because you're using an old version of the package (v1.2) and I've fixed a few bugs since then.
> 
> You project is in .NET Framework 4.7.2, if you're unable to upgrade it to .NET Core then I suggest updating the library to v2.2.0 which is the last version which worked with .NET Framework and will hopefully fix your issue.

**Comment by kodehelp22** [comment]
HI 
thanks for you replay.. I can upgrade to .net core because i'm are using it in MS BizTalk project.
But i will try your suggestions see if it fix the problem

**Comment by kodehelp22** [comment]
Hi again
I just tried with v2.20 of your PGPcore and still getting the same error that it can't finde the secret key.
I used this to upgrade: Install-Package PgpCore -Version 2.2.0

Does it work for you when you try my project!

The strange thing is that encryptions works fine, but getting the error when try to decrypt..

Could it also be that I Sign and i just wondering that I only provide the private key and the public key? When you look at myf code i provide public and private key in the encryptand sign method..?

**Comment by mattosaurus** [comment]
Ah, I think the issue is that you encrypt with the public key from your partner and then you sign with your private key but you are then trying to decrypt with your private key. The file can only be decrypted with your partners private key which I'm assuming you don't have access to.

**Comment by kodehelp22** [comment]
Ah.. you right.. I misunderstood the follow.. now i understand.. I have sent a pgp encrypt and signed test file to my partner as stated in my project and they accept the file and could decrypt.. so it works.. and as you mentioned i need their private key to decrypt.. 
Thanks for clearing the follow.. and a nice framework you have made..
